// src/api/request.ts
import axios, { AxiosResponse, HttpStatusCode } from 'axios'
import { toast } from 'react-hot-toast'

/**
 * use 'npm start' ,  NODE_ENV='development'.
 * use 'npm run build'  , NODE_ENV='production' , use Nginx Proxy
 */
const API_BASE_URL = process.env.NODE_ENV === 'development' ? 'http://localhost:5001/api/v1' : '/api/v1';

/**
 * Authentication Mechanism Overview:
 * 1. Generation & Storage: The ACCESS-TOKEN is generated by the back-end upon successful login.
 * 2. Automatic Transmission: All subsequent HTTP requests to the back-end server will automatically carry 
 *    the ACCESS-TOKEN within the HTTP Only Cookie.
 * 3. Token Expiry: This automatic carriage continues until the token's validity period has passed 
 * (or the cookie's maxAge is reached).
 */

const apiV1 = axios.create({
    baseURL: API_BASE_URL,
    timeout: 5000,
    //Ensure that HTTP Only cookies are carried while cross-domain request
    withCredentials: true,
});


apiV1.interceptors.response.use(
    //success: 2xx code
    (response: AxiosResponse) => {
        return response
    },
    //error
    (error) => {
        // 统一处理 401/403 等需要全局操作的错误 (例如，重定向到登录页)
        // if (status === HttpStatusCode.Unauthorized || status === HttpStatusCode.Forbidden) {
        //     // ... 处理未授权逻辑
        // }
        const msg =
            error?.response?.data?.message ||
            error?.message || '服务器错误，请稍后再试'
        toast.error(msg)

        error.displayMessage = msg

        return Promise.reject(error)
    }
)

export default apiV1
